export const FETCH_JOURNAL_ENTRIES_SUCCESS = 'FETCH_JOURNAL_ENTRIES_SUCCESS';
export const FETCH_JOURNAL_ENTRIES_REQUEST = 'FETCH_JOURNAL_ENTRIES_REQUEST';
export const FETCH_JOURNAL_ENTRIES_FAILURE = 'FETCH_JOURNAL_ENTRIES_FAILURE';

export const SAVE_JOURNAL_ENTRY_SUCCESS = 'SAVE_JOURNAL_ENTRY_SUCCESS';
export const UPDATE_JOURNAL_ENTRY_SUCCESS = 'UPDATE_JOURNAL_ENTRY_SUCCESS';
export const UPDATE_JOURNAL_ENTRY_FAILURE = 'UPDATE_JOURNAL_ENTRY_FAILURE';
